language: perl
sudo: false

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V

install:
  - cpan-install --deps
  # Install the right version of Devel::Cover, but no actual report module
  - COVERAGE=1 cpan-install --coverage

script:
  # unit tests
  - prove -r t/codecov
  - prove -r xt/codecov

  # integration tests
  - cd $TRAVIS_BUILD_DIR/t/data/proj
  - |-
    HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^t|^local/" \
    prove -r t
  - PERL5LIB=$TRAVIS_BUILD_DIR/lib travis_retry cover -report codecov

  - cd $TRAVIS_BUILD_DIR/t/data/proj_blib
  - |-
    HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^t|^local/" \
    prove --blib -r t
  - PERL5LIB=$TRAVIS_BUILD_DIR/lib travis_retry cover -report codecov

notifications:
  slack:
    - secure: "LiypVOGzfJoeTmdzkz2szBQIrflXFZZ4HFdVcaxeWe4bt1VT/f5l2sNd+lCcCarUjzKHfvqBvYOMusOJ2BuzA/6XIfwT7fN/QTkTwl9ARSC2Dk9xtjPeNFl97feCWirSlRVRALryO6oQOwaFO1ksGaCE4YVr1U0YqdLSvvCnebXN04o0o15QRHqGJJYLjwe/2y6rwVuKlCH9bRNZA6OUfv7W3noEHLJ4BnhC0DAZ9qR+anq7vgvIFyy4OadMMBMFcyymt3C1FA4MXI/X3UzmUbmUSKbXXvmeTYo8y0TS8Gtv46dOYCKxiGgODa/v6i6glPCY1KQvwVCsOq+z7xXPgK5HrfcZ/+tlLi40vhXWcroH0w8vlKMnsRKQ59Vg2pOM03vIXuM4T9s7i+KrLLW6M9DlESQeaCdENsUzBGeN9SffBJYR9Wy8rEJADShY2EKM4xaQjGGixX+Rx9m6j27O7WfSVEIcR7u+f8Kuzo5yCdeKUV198A+DdPm63LJoB3P8ccKbXsgF4tUUsGRPUOtARNzrInhrsG1tcQlV3XKKyJOiv0B/zADQO/dggfUh/Emv4heLCtapcihb3XYnUOGVywcBiNTsjk1GOMjzQSSsVxw+UhGWXrz1PPIWa6cbalem1YVBvwA3lh5tZEZkl7jsOrIrJGEiiTVw2Cbk3sBKMkk="

